# Generated by Django 4.1.2 on 2022-10-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_department_alter_employee_age_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
